### ISSUE TITLE
Adding timestamps to output

### ISSUE THREAD

**Issue by TmLev** [davidbarsky/tracing-tree#48]
I may have missed it, but how can one add timestamps to output of `tracing-tree`?

**Comment by davidbarsky** [comment]
Huh, I thought we could add timestamps to `tracing-tree`. We should probably add a builder option that accepts a [`FormatTime`](https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/time/trait.FormatTime.html).

**Comment by ten3roberts** [comment]
It seems that this issue and the linked ones haven't had any update for quite some time.

Is there any progress being done or is there something blocking these issues, or something else entirely?

I am just asking because I prefer tracing_tree over tracing_subscriber::fmt at it is easier to see what called what, and if it was called inside the same function invocation or not.

Thanks

**Comment by TmLev** [comment]
Sorry, I didn't have enough time to finish #49 (yes, I know, it shouldn't be too much work). I'll try again this week, but can't guarantee anything.

**Comment by belyakov-am** [comment]
Also very interested
